#!/usr/bin/env python3
"""
Comprehensive test for INVOICE PREVIEW = PDF DOWNLOAD = PRINT fix.

ROOT CAUSE: WeasyPrint was failing to import (missing python deps), so PDFs fell
back to reportlab template → downloaded PDF looked different from preview.

FIX: Installed WeasyPrint deps so build_invoice_pdf now renders the SAME HTML
template via WeasyPrint (identical to preview + print).

TESTS:
1. INVOICE PDF ENGINE - for each invoice type, verify PDF is generated by WeasyPrint
   (NOT reportlab - reportlab PDFs contain "ReportLab" string)
2. HTML PREVIEW WELL-FORMED - verify HTML contains proper content
3. SINGLE PAGE where expected - PDFs should be valid
4. ADMIN render endpoint - POST /api/invoices/render/pdf
5. ROLE ACCESS + REGRESSION - customer/partner/merchant can fetch their own
"""
import requests
import json
import sys
from datetime import datetime

BASE_URL = "https://azoapp-otp-preview.preview.emergentagent.com/api"
OTP = "123456"

# Test credentials
ADMIN_PHONE = "+919000000000"
MERCHANT_PHONE = "+919000000002"
PARTNER_PHONE = "+919000000003"
CUSTOMER_PHONE = "+919000000004"

class Colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    RESET = '\033[0m'
    BOLD = '\033[1m'

def log(msg, color=Colors.RESET):
    print(f"{color}{msg}{Colors.RESET}")

def login(phone):
    """Login and return auth token"""
    log(f"\n🔐 Logging in as {phone}...", Colors.BLUE)
    
    # Request OTP
    resp = requests.post(f"{BASE_URL}/auth/send-otp", json={"phone": phone})
    if resp.status_code != 200:
        log(f"❌ OTP request failed: {resp.status_code} {resp.text}", Colors.RED)
        return None
    
    # Verify OTP
    resp = requests.post(f"{BASE_URL}/auth/verify-otp", json={"phone": phone, "otp": OTP})
    if resp.status_code != 200:
        log(f"❌ OTP verify failed: {resp.status_code} {resp.text}", Colors.RED)
        return None
    
    data = resp.json()
    token = data.get("token")
    log(f"✅ Logged in successfully", Colors.GREEN)
    return token

def get_invoices_by_type(token, invoice_type):
    """Get invoices of a specific type"""
    headers = {"Authorization": f"Bearer {token}"}
    params = {"invoice_type": invoice_type, "page_size": 50}
    resp = requests.get(f"{BASE_URL}/invoices", headers=headers, params=params)
    if resp.status_code != 200:
        return []
    data = resp.json()
    return data.get("invoices", [])

def test_pdf_engine(token, invoice_id, invoice_type, invoice_number):
    """
    TEST 1: INVOICE PDF ENGINE
    - Verify PDF is generated by WeasyPrint (NOT reportlab)
    - reportlab PDFs contain "ReportLab" string, WeasyPrint ones don't
    """
    log(f"\n📄 Testing PDF for {invoice_type} invoice {invoice_number}...", Colors.BLUE)
    
    headers = {"Authorization": f"Bearer {token}"}
    resp = requests.get(f"{BASE_URL}/invoices/{invoice_id}/pdf", headers=headers)
    
    # Check HTTP status
    if resp.status_code != 200:
        log(f"  ❌ HTTP {resp.status_code} (expected 200)", Colors.RED)
        return False
    log(f"  ✅ HTTP 200", Colors.GREEN)
    
    # Check content-type
    content_type = resp.headers.get("content-type", "")
    if "application/pdf" not in content_type and "application/octet-stream" not in content_type:
        log(f"  ❌ Content-Type: {content_type} (expected application/pdf)", Colors.RED)
        return False
    log(f"  ✅ Content-Type: {content_type}", Colors.GREEN)
    
    # Check PDF magic bytes
    pdf_bytes = resp.content
    if len(pdf_bytes) == 0:
        log(f"  ❌ Empty PDF body", Colors.RED)
        return False
    log(f"  ✅ PDF body size: {len(pdf_bytes)} bytes", Colors.GREEN)
    
    if not pdf_bytes.startswith(b"%PDF"):
        log(f"  ❌ PDF does not start with %PDF magic bytes", Colors.RED)
        return False
    log(f"  ✅ PDF starts with %PDF magic bytes", Colors.GREEN)
    
    # CRITICAL: Check if PDF was generated by WeasyPrint (NOT reportlab)
    # reportlab PDFs contain the literal "ReportLab" producer string
    # WeasyPrint PDFs do NOT contain "ReportLab"
    first_3000_bytes = pdf_bytes[:3000]
    if b"ReportLab" in first_3000_bytes:
        log(f"  ❌ CRITICAL: PDF contains 'ReportLab' in first 3000 bytes - PDF was generated by reportlab fallback, NOT WeasyPrint!", Colors.RED)
        return False
    log(f"  ✅ CRITICAL: PDF does NOT contain 'ReportLab' - PDF was generated by WeasyPrint", Colors.GREEN)
    
    # Check entire PDF for ReportLab (ideally should not appear anywhere)
    if b"ReportLab" in pdf_bytes:
        log(f"  ⚠️  WARNING: PDF contains 'ReportLab' somewhere (not in first 3000 bytes)", Colors.YELLOW)
    else:
        log(f"  ✅ PDF does NOT contain 'ReportLab' anywhere - confirmed WeasyPrint", Colors.GREEN)
    
    return True

def test_html_preview(token, invoice_id, invoice_type, invoice_number):
    """
    TEST 2: HTML PREVIEW WELL-FORMED
    - Verify HTML contains proper content and key financial labels
    """
    log(f"\n🌐 Testing HTML preview for {invoice_type} invoice {invoice_number}...", Colors.BLUE)
    
    headers = {"Authorization": f"Bearer {token}"}
    resp = requests.get(f"{BASE_URL}/invoices/{invoice_id}/view", headers=headers)
    
    # Check HTTP status
    if resp.status_code != 200:
        log(f"  ❌ HTTP {resp.status_code} (expected 200)", Colors.RED)
        return False
    log(f"  ✅ HTTP 200", Colors.GREEN)
    
    # Check content-type
    content_type = resp.headers.get("content-type", "")
    if "text/html" not in content_type:
        log(f"  ❌ Content-Type: {content_type} (expected text/html)", Colors.RED)
        return False
    log(f"  ✅ Content-Type: {content_type}", Colors.GREEN)
    
    html = resp.text
    
    # Check HTML structure
    if "<html" not in html.lower():
        log(f"  ❌ HTML does not contain <html tag", Colors.RED)
        return False
    log(f"  ✅ HTML contains <html tag", Colors.GREEN)
    
    # Check invoice number
    if invoice_number not in html:
        log(f"  ❌ HTML does not contain invoice number {invoice_number}", Colors.RED)
        return False
    log(f"  ✅ HTML contains invoice number {invoice_number}", Colors.GREEN)
    
    # Check key financial labels based on invoice type
    if invoice_type == "cancellation":
        # For cancellation: should have "Total Customer Refund" and NOT "Cancellation Charge"
        if "Total Customer Refund" not in html:
            log(f"  ❌ Cancellation invoice does NOT contain 'Total Customer Refund'", Colors.RED)
            return False
        log(f"  ✅ Cancellation invoice contains 'Total Customer Refund'", Colors.GREEN)
        
        if "Cancellation Charge" in html:
            log(f"  ❌ Cancellation invoice contains 'Cancellation Charge' (should not)", Colors.RED)
            return False
        log(f"  ✅ Cancellation invoice does NOT contain 'Cancellation Charge'", Colors.GREEN)
    
    elif invoice_type == "booking":
        # For tax invoice: should have "TOTAL" or "Total"
        if "TOTAL" not in html.upper():
            log(f"  ❌ Tax invoice does NOT contain 'TOTAL'", Colors.RED)
            return False
        log(f"  ✅ Tax invoice contains 'TOTAL'", Colors.GREEN)
    
    return True

def test_admin_render_endpoint(admin_token):
    """
    TEST 4: ADMIN render endpoint
    - POST /api/invoices/render/pdf with minimal payload
    """
    log(f"\n🔧 Testing admin render endpoint...", Colors.BLUE)
    
    headers = {"Authorization": f"Bearer {admin_token}"}
    
    # Minimal valid payload
    payload = {
        "invoice_number": "TEST-2026-001",
        "invoice_type": "booking",
        "status": "issued",
        "payment_status": "paid",
        "currency": "INR",
        "line_items": [
            {"desc": "Test Service", "qty": 1, "amount": 500.0}
        ],
        "subtotal": 500.0,
        "tax": 90.0,
        "total_amount": 590.0,
        "customer_snapshot": {
            "name": "Test Customer",
            "phone": "+919000000004"
        },
        "business_snapshot": {
            "name": "AzoApp",
            "currency": "INR"
        }
    }
    
    resp = requests.post(f"{BASE_URL}/invoices/render/pdf", headers=headers, json=payload)
    
    if resp.status_code != 200:
        log(f"  ❌ HTTP {resp.status_code} (expected 200)", Colors.RED)
        log(f"  Response: {resp.text[:200]}", Colors.RED)
        return False
    log(f"  ✅ HTTP 200", Colors.GREEN)
    
    # Check content-type
    content_type = resp.headers.get("content-type", "")
    if "application/pdf" not in content_type:
        log(f"  ❌ Content-Type: {content_type} (expected application/pdf)", Colors.RED)
        return False
    log(f"  ✅ Content-Type: {content_type}", Colors.GREEN)
    
    # Check PDF
    pdf_bytes = resp.content
    if len(pdf_bytes) == 0 or not pdf_bytes.startswith(b"%PDF"):
        log(f"  ❌ Invalid PDF", Colors.RED)
        return False
    log(f"  ✅ Valid PDF ({len(pdf_bytes)} bytes)", Colors.GREEN)
    
    # Check WeasyPrint
    if b"ReportLab" in pdf_bytes[:3000]:
        log(f"  ❌ CRITICAL: PDF contains 'ReportLab' - using reportlab fallback", Colors.RED)
        return False
    log(f"  ✅ CRITICAL: PDF generated by WeasyPrint", Colors.GREEN)
    
    return True

def test_role_access(customer_token, partner_token, merchant_token, admin_token):
    """
    TEST 5: ROLE ACCESS + REGRESSION
    - Customer can fetch their own invoice
    - Partner can fetch their own invoice
    - Merchant can fetch their own invoice
    - Cross-user access is blocked (403/404)
    """
    log(f"\n🔒 Testing role-based access control...", Colors.BLUE)
    
    # Get customer invoices
    log(f"\n  Testing customer access...", Colors.BLUE)
    customer_headers = {"Authorization": f"Bearer {customer_token}"}
    resp = requests.get(f"{BASE_URL}/invoices", headers=customer_headers)
    if resp.status_code != 200:
        log(f"    ❌ Customer cannot fetch their invoices: {resp.status_code}", Colors.RED)
        return False
    customer_invoices = resp.json().get("invoices", [])
    log(f"    ✅ Customer can fetch their invoices ({len(customer_invoices)} found)", Colors.GREEN)
    
    if customer_invoices:
        # Customer can fetch their own invoice PDF
        invoice_id = customer_invoices[0]["id"]
        resp = requests.get(f"{BASE_URL}/invoices/{invoice_id}/pdf", headers=customer_headers)
        if resp.status_code != 200:
            log(f"    ❌ Customer cannot fetch their own invoice PDF: {resp.status_code}", Colors.RED)
            return False
        log(f"    ✅ Customer can fetch their own invoice PDF", Colors.GREEN)
    
    # Get partner invoices
    log(f"\n  Testing partner access...", Colors.BLUE)
    partner_headers = {"Authorization": f"Bearer {partner_token}"}
    resp = requests.get(f"{BASE_URL}/invoices", headers=partner_headers)
    if resp.status_code != 200:
        log(f"    ❌ Partner cannot fetch their invoices: {resp.status_code}", Colors.RED)
        return False
    partner_invoices = resp.json().get("invoices", [])
    log(f"    ✅ Partner can fetch their invoices ({len(partner_invoices)} found)", Colors.GREEN)
    
    # Get merchant invoices
    log(f"\n  Testing merchant access...", Colors.BLUE)
    merchant_headers = {"Authorization": f"Bearer {merchant_token}"}
    resp = requests.get(f"{BASE_URL}/invoices", headers=merchant_headers)
    if resp.status_code != 200:
        log(f"    ❌ Merchant cannot fetch their invoices: {resp.status_code}", Colors.RED)
        return False
    merchant_invoices = resp.json().get("invoices", [])
    log(f"    ✅ Merchant can fetch their invoices ({len(merchant_invoices)} found)", Colors.GREEN)
    
    # Test cross-user access (customer trying to access partner invoice)
    if partner_invoices and customer_invoices:
        log(f"\n  Testing cross-user access blocking...", Colors.BLUE)
        partner_invoice_id = partner_invoices[0]["id"]
        resp = requests.get(f"{BASE_URL}/invoices/{partner_invoice_id}/pdf", headers=customer_headers)
        if resp.status_code == 200:
            log(f"    ❌ Customer can access partner invoice (should be blocked)", Colors.RED)
            return False
        if resp.status_code not in [403, 404]:
            log(f"    ⚠️  Unexpected status code {resp.status_code} (expected 403 or 404)", Colors.YELLOW)
        log(f"    ✅ Cross-user access blocked ({resp.status_code})", Colors.GREEN)
    
    return True

def main():
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"INVOICE PREVIEW = PDF DOWNLOAD = PRINT FIX - COMPREHENSIVE TEST", Colors.BOLD)
    log(f"{'='*80}\n", Colors.BOLD)
    
    log(f"BASE_URL: {BASE_URL}", Colors.BLUE)
    log(f"Test Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", Colors.BLUE)
    
    # Login all users
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"AUTHENTICATION", Colors.BOLD)
    log(f"{'='*80}", Colors.BOLD)
    
    admin_token = login(ADMIN_PHONE)
    merchant_token = login(MERCHANT_PHONE)
    partner_token = login(PARTNER_PHONE)
    customer_token = login(CUSTOMER_PHONE)
    
    if not all([admin_token, merchant_token, partner_token, customer_token]):
        log(f"\n❌ Authentication failed for one or more users", Colors.RED)
        return 1
    
    # Get invoices for each type
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"FETCHING INVOICES", Colors.BOLD)
    log(f"{'='*80}", Colors.BOLD)
    
    invoice_types = ["booking", "cancellation", "refund", "withdrawal"]
    invoices_by_type = {}
    
    for inv_type in invoice_types:
        log(f"\n🔍 Fetching {inv_type} invoices...", Colors.BLUE)
        
        # Try admin first (can see all)
        invoices = get_invoices_by_type(admin_token, inv_type)
        
        if not invoices:
            # Try customer
            invoices = get_invoices_by_type(customer_token, inv_type)
        
        if not invoices:
            # Try partner
            invoices = get_invoices_by_type(partner_token, inv_type)
        
        if not invoices:
            # Try merchant
            invoices = get_invoices_by_type(merchant_token, inv_type)
        
        if invoices:
            invoices_by_type[inv_type] = invoices[0]  # Take first invoice
            log(f"  ✅ Found {inv_type} invoice: {invoices[0]['invoice_number']}", Colors.GREEN)
        else:
            log(f"  ⚠️  No {inv_type} invoices found", Colors.YELLOW)
    
    if not invoices_by_type:
        log(f"\n❌ No invoices found to test", Colors.RED)
        return 1
    
    # Run tests
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"TEST 1 & 2: PDF ENGINE + HTML PREVIEW", Colors.BOLD)
    log(f"{'='*80}", Colors.BOLD)
    
    test_results = {
        "pdf_engine": {},
        "html_preview": {},
        "admin_render": False,
        "role_access": False
    }
    
    for inv_type, invoice in invoices_by_type.items():
        invoice_id = invoice["id"]
        invoice_number = invoice["invoice_number"]
        
        # Determine which token to use based on invoice owner
        if invoice.get("customer_id"):
            token = customer_token
        elif invoice.get("partner_id"):
            token = partner_token
        elif invoice.get("merchant_id"):
            token = merchant_token
        else:
            token = admin_token
        
        # Test PDF engine
        pdf_pass = test_pdf_engine(token, invoice_id, inv_type, invoice_number)
        test_results["pdf_engine"][inv_type] = pdf_pass
        
        # Test HTML preview
        html_pass = test_html_preview(token, invoice_id, inv_type, invoice_number)
        test_results["html_preview"][inv_type] = html_pass
    
    # Test admin render endpoint
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"TEST 4: ADMIN RENDER ENDPOINT", Colors.BOLD)
    log(f"{'='*80}", Colors.BOLD)
    
    test_results["admin_render"] = test_admin_render_endpoint(admin_token)
    
    # Test role access
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"TEST 5: ROLE ACCESS + REGRESSION", Colors.BOLD)
    log(f"{'='*80}", Colors.BOLD)
    
    test_results["role_access"] = test_role_access(customer_token, partner_token, merchant_token, admin_token)
    
    # Summary
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"TEST SUMMARY", Colors.BOLD)
    log(f"{'='*80}\n", Colors.BOLD)
    
    total_tests = 0
    passed_tests = 0
    
    log(f"TEST 1: INVOICE PDF ENGINE (WeasyPrint vs ReportLab)", Colors.BOLD)
    for inv_type, result in test_results["pdf_engine"].items():
        total_tests += 1
        if result:
            passed_tests += 1
            log(f"  ✅ {inv_type.upper()}: PASS", Colors.GREEN)
        else:
            log(f"  ❌ {inv_type.upper()}: FAIL", Colors.RED)
    
    log(f"\nTEST 2: HTML PREVIEW WELL-FORMED", Colors.BOLD)
    for inv_type, result in test_results["html_preview"].items():
        total_tests += 1
        if result:
            passed_tests += 1
            log(f"  ✅ {inv_type.upper()}: PASS", Colors.GREEN)
        else:
            log(f"  ❌ {inv_type.upper()}: FAIL", Colors.RED)
    
    log(f"\nTEST 4: ADMIN RENDER ENDPOINT", Colors.BOLD)
    total_tests += 1
    if test_results["admin_render"]:
        passed_tests += 1
        log(f"  ✅ PASS", Colors.GREEN)
    else:
        log(f"  ❌ FAIL", Colors.RED)
    
    log(f"\nTEST 5: ROLE ACCESS + REGRESSION", Colors.BOLD)
    total_tests += 1
    if test_results["role_access"]:
        passed_tests += 1
        log(f"  ✅ PASS", Colors.GREEN)
    else:
        log(f"  ❌ FAIL", Colors.RED)
    
    # Overall result
    log(f"\n{'='*80}", Colors.BOLD)
    success_rate = (passed_tests / total_tests * 100) if total_tests > 0 else 0
    
    if passed_tests == total_tests:
        log(f"✅ ALL TESTS PASSED ({passed_tests}/{total_tests}) - 100%", Colors.GREEN + Colors.BOLD)
        log(f"\n🎉 INVOICE PREVIEW = PDF DOWNLOAD = PRINT FIX IS WORKING!", Colors.GREEN + Colors.BOLD)
        log(f"   WeasyPrint is generating PDFs from the SAME HTML template as preview.", Colors.GREEN)
        return_code = 0
    else:
        log(f"❌ SOME TESTS FAILED ({passed_tests}/{total_tests}) - {success_rate:.1f}%", Colors.RED + Colors.BOLD)
        return_code = 1
    
    log(f"{'='*80}\n", Colors.BOLD)
    
    return return_code

if __name__ == "__main__":
    sys.exit(main())
