#!/usr/bin/env python3
"""
Comprehensive test for INVOICE PREVIEW = PDF DOWNLOAD = PRINT fix.
"""
import requests
import json
import sys
from datetime import datetime

BASE_URL = "https://fcm-token-fix-3.preview.emergentagent.com/api"
OTP = "123456"

ADMIN_PHONE = "+919000000000"
CUSTOMER_PHONE = "+919000000004"

class Colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    RESET = '\033[0m'
    BOLD = '\033[1m'

def log(msg, color=Colors.RESET):
    print(f"{color}{msg}{Colors.RESET}")

def login(phone):
    """Login and return auth token"""
    log(f"🔐 Logging in as {phone}...", Colors.BLUE)
    resp = requests.post(f"{BASE_URL}/auth/send-otp", json={"phone": phone})
    if resp.status_code != 200:
        log(f"❌ OTP request failed: {resp.status_code}", Colors.RED)
        return None
    resp = requests.post(f"{BASE_URL}/auth/verify-otp", json={"phone": phone, "otp": OTP})
    if resp.status_code != 200:
        log(f"❌ OTP verify failed: {resp.status_code}", Colors.RED)
        return None
    token = resp.json().get("token")
    log(f"✅ Logged in successfully", Colors.GREEN)
    return token

def test_admin_render_pdf(admin_token):
    """Test admin render endpoint with all invoice types"""
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"TEST: ADMIN RENDER ENDPOINT (WeasyPrint vs ReportLab)", Colors.BOLD)
    log(f"{'='*80}\n", Colors.BOLD)
    
    headers = {"Authorization": f"Bearer {admin_token}"}
    
    invoice_types = [
        ("booking", "Tax Invoice"),
        ("cancellation", "Cancellation Note"),
        ("refund", "Refund Document"),
        ("withdrawal", "Withdrawal Statement")
    ]
    
    results = {}
    
    for inv_type, label in invoice_types:
        log(f"\n📄 Testing {label} ({inv_type})...", Colors.BLUE)
        
        # Build payload based on invoice type
        payload = {
            "invoice_number": f"TEST-{inv_type.upper()}-001",
            "invoice_type": inv_type,
            "status": "issued",
            "payment_status": "paid",
            "currency": "INR",
            "line_items": [
                {"desc": "AC Deep Clean", "qty": 1, "amount": 999.0},
                {"desc": "+ Gas Refill", "detail": "Add-on", "qty": 1, "amount": 500.0}
            ],
            "subtotal": 1499.0,
            "tax": 269.82,
            "total_amount": 1768.82,
            "customer_snapshot": {
                "name": "Priya Verma",
                "phone": "+91 90000 00004",
                "address": "12 Kankarbagh Main Road, Patna, Bihar 800020"
            },
            "business_snapshot": {
                "name": "AzoApp",
                "currency": "INR"
            }
        }
        
        # Add type-specific fields
        if inv_type == "cancellation":
            payload["original_amount"] = 1768.82
            payload["cancellation_pct"] = 80
            payload["service_refund"] = 1199.2
            payload["gst_refund"] = 215.86
            payload["refund"] = 1415.06
        elif inv_type == "refund":
            payload["refund"] = 1415.06
        
        resp = requests.post(f"{BASE_URL}/invoices/render/pdf", headers=headers, json=payload)
        
        # Check HTTP status
        if resp.status_code != 200:
            log(f"  ❌ HTTP {resp.status_code} (expected 200)", Colors.RED)
            log(f"  Response: {resp.text[:200]}", Colors.RED)
            results[inv_type] = False
            continue
        log(f"  ✅ HTTP 200", Colors.GREEN)
        
        # Check content-type
        content_type = resp.headers.get("content-type", "")
        if "application/pdf" not in content_type:
            log(f"  ❌ Content-Type: {content_type} (expected application/pdf)", Colors.RED)
            results[inv_type] = False
            continue
        log(f"  ✅ Content-Type: {content_type}", Colors.GREEN)
        
        # Check PDF
        pdf_bytes = resp.content
        if len(pdf_bytes) == 0:
            log(f"  ❌ Empty PDF body", Colors.RED)
            results[inv_type] = False
            continue
        log(f"  ✅ PDF body size: {len(pdf_bytes)} bytes", Colors.GREEN)
        
        if not pdf_bytes.startswith(b"%PDF"):
            log(f"  ❌ PDF does not start with %PDF magic bytes", Colors.RED)
            results[inv_type] = False
            continue
        log(f"  ✅ PDF starts with %PDF magic bytes", Colors.GREEN)
        
        # CRITICAL: Check if PDF was generated by WeasyPrint (NOT reportlab)
        first_3000_bytes = pdf_bytes[:3000]
        if b"ReportLab" in first_3000_bytes:
            log(f"  ❌ CRITICAL: PDF contains 'ReportLab' in first 3000 bytes", Colors.RED)
            log(f"     → PDF was generated by reportlab fallback, NOT WeasyPrint!", Colors.RED)
            results[inv_type] = False
            continue
        log(f"  ✅ CRITICAL: PDF does NOT contain 'ReportLab' in first 3000 bytes", Colors.GREEN)
        
        # Check entire PDF
        if b"ReportLab" in pdf_bytes:
            log(f"  ⚠️  WARNING: PDF contains 'ReportLab' somewhere else", Colors.YELLOW)
        else:
            log(f"  ✅ PDF does NOT contain 'ReportLab' anywhere - confirmed WeasyPrint", Colors.GREEN)
        
        results[inv_type] = True
    
    return results

def test_admin_render_html(admin_token):
    """Test admin render HTML endpoint"""
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"TEST: ADMIN RENDER HTML ENDPOINT", Colors.BOLD)
    log(f"{'='*80}\n", Colors.BOLD)
    
    headers = {"Authorization": f"Bearer {admin_token}"}
    
    invoice_types = [
        ("booking", "Tax Invoice"),
        ("cancellation", "Cancellation Note")
    ]
    
    results = {}
    
    for inv_type, label in invoice_types:
        log(f"\n🌐 Testing {label} HTML ({inv_type})...", Colors.BLUE)
        
        payload = {
            "invoice_number": f"TEST-{inv_type.upper()}-001",
            "invoice_type": inv_type,
            "status": "issued",
            "payment_status": "paid",
            "currency": "INR",
            "line_items": [
                {"desc": "AC Deep Clean", "qty": 1, "amount": 999.0}
            ],
            "subtotal": 999.0,
            "tax": 179.82,
            "total_amount": 1178.82,
            "customer_snapshot": {
                "name": "Priya Verma",
                "phone": "+91 90000 00004"
            },
            "business_snapshot": {
                "name": "AzoApp",
                "currency": "INR"
            }
        }
        
        if inv_type == "cancellation":
            payload["original_amount"] = 1178.82
            payload["cancellation_pct"] = 80
            payload["service_refund"] = 799.2
            payload["gst_refund"] = 143.86
            payload["refund"] = 943.06
        
        resp = requests.post(f"{BASE_URL}/invoices/render/html", headers=headers, json=payload)
        
        if resp.status_code != 200:
            log(f"  ❌ HTTP {resp.status_code}", Colors.RED)
            results[inv_type] = False
            continue
        log(f"  ✅ HTTP 200", Colors.GREEN)
        
        content_type = resp.headers.get("content-type", "")
        if "text/html" not in content_type:
            log(f"  ❌ Content-Type: {content_type}", Colors.RED)
            results[inv_type] = False
            continue
        log(f"  ✅ Content-Type: {content_type}", Colors.GREEN)
        
        html = resp.text
        
        if "<html" not in html.lower():
            log(f"  ❌ HTML does not contain <html tag", Colors.RED)
            results[inv_type] = False
            continue
        log(f"  ✅ HTML contains <html tag", Colors.GREEN)
        
        if f"TEST-{inv_type.upper()}-001" not in html:
            log(f"  ❌ HTML does not contain invoice number", Colors.RED)
            results[inv_type] = False
            continue
        log(f"  ✅ HTML contains invoice number", Colors.GREEN)
        
        # Check key financial labels
        if inv_type == "cancellation":
            if "Total Customer Refund" not in html:
                log(f"  ❌ Cancellation HTML does NOT contain 'Total Customer Refund'", Colors.RED)
                results[inv_type] = False
                continue
            log(f"  ✅ Cancellation HTML contains 'Total Customer Refund'", Colors.GREEN)
            
            if "Cancellation Charge" in html:
                log(f"  ❌ Cancellation HTML contains 'Cancellation Charge' (should not)", Colors.RED)
                results[inv_type] = False
                continue
            log(f"  ✅ Cancellation HTML does NOT contain 'Cancellation Charge'", Colors.GREEN)
        
        elif inv_type == "booking":
            if "TOTAL" not in html.upper():
                log(f"  ❌ Tax invoice HTML does NOT contain 'TOTAL'", Colors.RED)
                results[inv_type] = False
                continue
            log(f"  ✅ Tax invoice HTML contains 'TOTAL'", Colors.GREEN)
        
        results[inv_type] = True
    
    return results

def main():
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"INVOICE PREVIEW = PDF DOWNLOAD = PRINT FIX - COMPREHENSIVE TEST", Colors.BOLD)
    log(f"{'='*80}\n", Colors.BOLD)
    
    log(f"BASE_URL: {BASE_URL}", Colors.BLUE)
    log(f"Test Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", Colors.BLUE)
    
    # Login
    admin_token = login(ADMIN_PHONE)
    if not admin_token:
        log(f"\n❌ Admin authentication failed", Colors.RED)
        return 1
    
    # Test admin render PDF endpoint
    pdf_results = test_admin_render_pdf(admin_token)
    
    # Test admin render HTML endpoint
    html_results = test_admin_render_html(admin_token)
    
    # Summary
    log(f"\n{'='*80}", Colors.BOLD)
    log(f"TEST SUMMARY", Colors.BOLD)
    log(f"{'='*80}\n", Colors.BOLD)
    
    total_tests = 0
    passed_tests = 0
    
    log(f"PDF RENDER TESTS (WeasyPrint vs ReportLab):", Colors.BOLD)
    for inv_type, result in pdf_results.items():
        total_tests += 1
        if result:
            passed_tests += 1
            log(f"  ✅ {inv_type.upper()}: PASS", Colors.GREEN)
        else:
            log(f"  ❌ {inv_type.upper()}: FAIL", Colors.RED)
    
    log(f"\nHTML RENDER TESTS:", Colors.BOLD)
    for inv_type, result in html_results.items():
        total_tests += 1
        if result:
            passed_tests += 1
            log(f"  ✅ {inv_type.upper()}: PASS", Colors.GREEN)
        else:
            log(f"  ❌ {inv_type.upper()}: FAIL", Colors.RED)
    
    log(f"\n{'='*80}", Colors.BOLD)
    success_rate = (passed_tests / total_tests * 100) if total_tests > 0 else 0
    
    if passed_tests == total_tests:
        log(f"✅ ALL TESTS PASSED ({passed_tests}/{total_tests}) - 100%", Colors.GREEN + Colors.BOLD)
        log(f"\n🎉 INVOICE PREVIEW = PDF DOWNLOAD = PRINT FIX IS WORKING!", Colors.GREEN + Colors.BOLD)
        log(f"   WeasyPrint is generating PDFs from the SAME HTML template as preview.", Colors.GREEN)
        return_code = 0
    else:
        log(f"❌ SOME TESTS FAILED ({passed_tests}/{total_tests}) - {success_rate:.1f}%", Colors.RED + Colors.BOLD)
        return_code = 1
    
    log(f"{'='*80}\n", Colors.BOLD)
    
    return return_code

if __name__ == "__main__":
    sys.exit(main())
