name: Build Customer Android APK

defaults:
  tools:
    node: "22"

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Customer Android APK
    type: build
    params:
      platform: android
      profile: production-apk
