const js = require("@eslint/js");
const react = require("eslint-plugin-react");
const reactHooks = require("eslint-plugin-react-hooks");

module.exports = [
  { ignores: ["build/**", "node_modules/**", "public/**"] },
  js.configs.recommended,
  {
    files: ["**/*.config.js", "plugins/**/*.js", "src/setupProxy.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        require: "readonly", module: "writable", process: "readonly", __dirname: "readonly",
        __filename: "readonly", console: "readonly", exports: "writable", Buffer: "readonly",
        setTimeout: "readonly", clearTimeout: "readonly", setInterval: "readonly", clearInterval: "readonly",
      },
    },
    rules: { "no-undef": "off" },
  },
  {
    files: ["src/**/*.{js,jsx}"],
    plugins: { react, "react-hooks": reactHooks },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: {
        window: "readonly", document: "readonly", navigator: "readonly", localStorage: "readonly", sessionStorage: "readonly",
        console: "readonly", setTimeout: "readonly", clearTimeout: "readonly", setInterval: "readonly", clearInterval: "readonly",
        fetch: "readonly", URL: "readonly", URLSearchParams: "readonly", FormData: "readonly", Blob: "readonly", File: "readonly",
        FileReader: "readonly", Image: "readonly", Audio: "readonly", AudioContext: "readonly", CustomEvent: "readonly", Event: "readonly",
        EventSource: "readonly", Notification: "readonly", process: "readonly", requestAnimationFrame: "readonly", cancelAnimationFrame: "readonly",
        MutationObserver: "readonly", IntersectionObserver: "readonly", ResizeObserver: "readonly", AbortController: "readonly", Promise: "readonly",
        HTMLElement: "readonly", Element: "readonly", Node: "readonly", history: "readonly", location: "readonly", alert: "readonly", confirm: "readonly",
        prompt: "readonly", atob: "readonly", btoa: "readonly", crypto: "readonly", performance: "readonly", screen: "readonly", getComputedStyle: "readonly",
        structuredClone: "readonly", queueMicrotask: "readonly", TextEncoder: "readonly", TextDecoder: "readonly", DOMParser: "readonly", XMLSerializer: "readonly",
        MediaRecorder: "readonly", ImageCapture: "readonly", google: "readonly", self: "readonly", caches: "readonly", clients: "readonly", registration: "readonly",
        importScripts: "readonly", firebase: "readonly", Razorpay: "readonly", html2canvas: "readonly", jspdf: "readonly", speechSynthesis: "readonly",
        SpeechSynthesisUtterance: "readonly", webkitSpeechRecognition: "readonly", SpeechRecognition: "readonly", matchMedia: "readonly", scrollTo: "readonly",
        open: "readonly", print: "readonly", innerWidth: "readonly", innerHeight: "readonly", devicePixelRatio: "readonly", indexedDB: "readonly",
        BroadcastChannel: "readonly", ServiceWorkerRegistration: "readonly", PushManager: "readonly", Worker: "readonly", WebSocket: "readonly", Headers: "readonly",
        Request: "readonly", Response: "readonly", MessageChannel: "readonly", KeyboardEvent: "readonly", MouseEvent: "readonly", TouchEvent: "readonly",
        HTMLCanvasElement: "readonly", HTMLInputElement: "readonly", HTMLImageElement: "readonly", HTMLVideoElement: "readonly", ClipboardItem: "readonly",
        NodeList: "readonly", DataTransfer: "readonly", Path2D: "readonly", OffscreenCanvas: "readonly", createImageBitmap: "readonly", Intl: "readonly",
      },
    },
    settings: { react: { version: "detect" } },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      "react/no-unescaped-entities": "off",
      "react/display-name": "off",
      "no-unused-vars": "warn",
      "no-dupe-keys": "warn",
      "no-empty": "warn",
      "no-undef": "warn",
      "no-useless-escape": "warn",
      "no-prototype-builtins": "warn",
      "no-case-declarations": "warn",
      "no-fallthrough": "warn",
      "no-cond-assign": "warn",
      "no-constant-condition": "warn",
      "no-control-regex": "warn",
      "no-unsafe-optional-chaining": "warn",
      "react-hooks/exhaustive-deps": "warn",
      "react-hooks/rules-of-hooks": "warn",
      "react/jsx-key": "warn",
      "react/no-unknown-property": "warn",
      "react/jsx-no-target-blank": "warn",
    },
  },
];
