[program:customer_expo]
command=/bin/sh /app/Customer/scripts/start-expo.sh
directory=/app/Customer
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/supervisor/customer_expo.err.log
stdout_logfile=/var/log/supervisor/customer_expo.out.log
